###
POST http://localhost:4000/api/auth/login
Content-Type: application/json

{
 "email": "f.bencharef@esi-sba.dz",
 "password": "fatima"
}
###
GET http://localhost:4000/api/users/AllUsers
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTAwLCJpYXQiOjE3MTIwNDA0NDcsImV4cCI6MTcxMjEyNjg0N30.TeeaioyQ_DqrJPz9kCfckE3-d8LpHN_m_KhuLnKGwj4
Content-Type: application/json

###
POST http://localhost:4000/api/users/createuser
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NTcsImlhdCI6MTcxMTU0NDA3NywiZXhwIjoxNzExNjMwNDc3fQ.B4rREhfTgrBGqs7TIWpbprCXS1yQgCD-ezJJd6zBND4
Content-Type: application/json

{
"firstname":"fatima",
"lastname":"fatima",
"email":"f.bencharef@esi-sba.dz",
"phone":"07777",
"password" : "fatima",
"isactive":true,
"role" : "admin"
}

### 

DELETE  http://localhost:4000/api/users/strucutreresponsable2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTI5LCJpYXQiOjE3MTIwNzcxODIsImV4cCI6MTcxMjE2MzU4Mn0.HNNrwT2_cUwRwifMBIp68gibuZJ145VFPk1yD4Zy1so
Content-Type: application/json

###

PUT  http://localhost:4000/api/users/modifyParams
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NTcsImlhdCI6MTcxMTU0NDA3NywiZXhwIjoxNzExNjMwNDc3fQ.B4rREhfTgrBGqs7TIWpbprCXS1yQgCD-ezJJd6zBND4
Content-Type: application/json

{
  "establishmentname" :"22",
  "image" :"22",
  "tauxtva" : 22
}
###
PUT  http://localhost:4000/api/users/f.bencharef@esi-sba.dz
Content-Type: application/json

{
"firstname":"bencharef",
"lastname":" bencharef",
"email1":"f.bencharef@esi-sba.dz",
"phone":"07777",
"isactive":true,
"password" : "fatima",
"role" : "admin"
}


###
POST   http://localhost:4000/api/users/createbackups
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NTcsImlhdCI6MTcxMTU0NDA3NywiZXhwIjoxNzExNjMwNDc3fQ.B4rREhfTgrBGqs7TIWpbprCXS1yQgCD-ezJJd6zBND4
Content-Type: application/json



### 
GET   http://localhost:4000/api/users/getAllBackups
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NTcsImlhdCI6MTcxMTU0NDA3NywiZXhwIjoxNzExNjMwNDc3fQ.B4rREhfTgrBGqs7TIWpbprCXS1yQgCD-ezJJd6zBND4
Content-Type: application/json


### 
POST http://localhost:4000/api/auth/forgot-password
Content-Type: application/json

{
 "email": "f.bencharef@esi-sba.dz"
}
###

POST http://localhost:4000/api/auth/reset-password/e385545f-a886-4380-bcb6-442d87d05117
Content-Type: application/json

{
"newPassword":"fatima",
"confirmPassword":"fatima"
}

### 
POST http://localhost:4000/api/users/activateaccount
Content-Type: application/json

{
 "email": "f.bencharef@esi-sba.dz"
}
### 
POST http://localhost:4000/api/users/deactivateAccount
Content-Type: application/json

{
 "email": "f.bencharef@esi-sba.dz"
}

### 
GET  http://localhost:4000/api/roles/getAllRoles
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NTcsImlhdCI6MTcxMTU0NDA3NywiZXhwIjoxNzExNjMwNDc3fQ.B4rREhfTgrBGqs7TIWpbprCXS1yQgCD-ezJJd6zBND4
Content-Type: application/json



####

GET  http://localhost:4000/api/permissions/getAllPermissions
Content-Type: application/json

###
POST http://localhost:4000/api/roles/update/2
Content-Type: application/json

{
 
  "permissions": [
  "Create user",
  "delete user",
  "deactivate account"
  ]
}

###

POST http://localhost:4000/api/auth/logout
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTI5LCJpYXQiOjE3MTIwNjI1MjgsImV4cCI6MTcxMjE0ODkyOH0.1uaHt7FvgTu9tv1vfZ1JuGhcKmgSU21xPEqieeKW0g0
Content-Type: application/json
###
GET  http://localhost:4000/api/structures/allstructures
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NTcsImlhdCI6MTcxMTU0NDA3NywiZXhwIjoxNzExNjMwNDc3fQ.B4rREhfTgrBGqs7TIWpbprCXS1yQgCD-ezJJd6zBND4
Content-Type: application/json


###
GET  http://localhost:4000/api/structures/users/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NTcsImlhdCI6MTcxMTU0NDA3NywiZXhwIjoxNzExNjMwNDc3fQ.B4rREhfTgrBGqs7TIWpbprCXS1yQgCD-ezJJd6zBND4
Content-Type: application/json

###
DELETE http://localhost:4000/api/structures/delete/3

### 
GET http://localhost:4000/api/structures/responsable/1







### 
POST http://localhost:4000/api/bons/create/130

{
  "number": 123456,
  "orderdate": "2024-04-01",
  "deliverydate": "2024-04-15",
  "orderspecifications": "Example order specifications",
  "status": "Pending",
  "productDetails": [
    {
      "productId": 8,
      "orderedQuantity": 5
    },
    {
      "productId": 9,
      "orderedQuantity": 10
    }
  ]
}








