###
POST http://localhost:4000/api/auth/login
Content-Type: application/json

{
 "email": "achat@esi-sba.dz",
 "password": "123"
}
###
GET http://localhost:4000/api/users/AllUsers
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTAwLCJpYXQiOjE3MTIwNDA0NDcsImV4cCI6MTcxMjEyNjg0N30.TeeaioyQ_DqrJPz9kCfckE3-d8LpHN_m_KhuLnKGwj4
Content-Type: application/json

###
POST http://localhost:4000/api/users/createuser
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NTcsImlhdCI6MTcxMTU0NDA3NywiZXhwIjoxNzExNjMwNDc3fQ.B4rREhfTgrBGqs7TIWpbprCXS1yQgCD-ezJJd6zBND4
Content-Type: application/json

{
"firstname":"service",
"lastname":"m",
"email":"achat@esi-sba.dz",
"phone":"07777",
"password" : "123",
"isactive":true,
"role" : "agentserviceachat",
"id_structure":8
}

### 

DELETE  http://localhost:4000/api/users/strucutreresponsable2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTI5LCJpYXQiOjE3MTIwNzcxODIsImV4cCI6MTcxMjE2MzU4Mn0.HNNrwT2_cUwRwifMBIp68gibuZJ145VFPk1yD4Zy1so
Content-Type: application/json

###

PUT  http://localhost:4000/api/users/modifyParams
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NTcsImlhdCI6MTcxMTU0NDA3NywiZXhwIjoxNzExNjMwNDc3fQ.B4rREhfTgrBGqs7TIWpbprCXS1yQgCD-ezJJd6zBND4
Content-Type: application/json

{
  "establishmentname" :"22",
  "image" :"22",
  "tauxtva" : 22
}
###
PUT  http://localhost:4000/api/users/f.bencharef@esi-sba.dz
Content-Type: application/json

{
"firstname":"adminModifLast1",
"lastname":"4",
"newEmail":"f.bencharef@esi-sba.dz",
"phone":"07777",
"isactive":true,
"password" : "123",
"role": "admin"
}


###
POST   http://localhost:4000/api/users/createbackups
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NTcsImlhdCI6MTcxMTU0NDA3NywiZXhwIjoxNzExNjMwNDc3fQ.B4rREhfTgrBGqs7TIWpbprCXS1yQgCD-ezJJd6zBND4
Content-Type: application/json



### 
GET   http://localhost:4000/api/users/getAllBackups
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NTcsImlhdCI6MTcxMTU0NDA3NywiZXhwIjoxNzExNjMwNDc3fQ.B4rREhfTgrBGqs7TIWpbprCXS1yQgCD-ezJJd6zBND4
Content-Type: application/json


### 
POST http://localhost:4000/api/auth/forgot-password
Content-Type: application/json

{
 "email": "f.bencharef@esi-sba.dz"
}
###

POST http://localhost:4000/api/auth/reset-password/e385545f-a886-4380-bcb6-442d87d05117
Content-Type: application/json

{
"newPassword":"fatima",
"confirmPassword":"fatima"
}

### 
POST http://localhost:4000/api/users/activateaccount
Content-Type: application/json

{
 "email": "f.bencharef@esi-sba.dz"
}
### 
POST http://localhost:4000/api/users/deactivateAccount
Content-Type: application/json

{
 "email": "f.bencharef@esi-sba.dz"
}

### 
GET  http://localhost:4000/api/roles/getAllRoles
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NTcsImlhdCI6MTcxMTU0NDA3NywiZXhwIjoxNzExNjMwNDc3fQ.B4rREhfTgrBGqs7TIWpbprCXS1yQgCD-ezJJd6zBND4
Content-Type: application/json



####

GET  http://localhost:4000/api/permissions/getAllPermissions
Content-Type: application/json

###
POST http://localhost:4000/api/roles/update/2
Content-Type: application/json

{
 
  "permissions": [
  "Create user",
  "delete user",
  "deactivate account"
  ]
}

###

POST http://localhost:4000/api/auth/logout
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTI5LCJpYXQiOjE3MTIwNjI1MjgsImV4cCI6MTcxMjE0ODkyOH0.1uaHt7FvgTu9tv1vfZ1JuGhcKmgSU21xPEqieeKW0g0
Content-Type: application/json
###
GET  http://localhost:4000/api/structures/allstructures
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NTcsImlhdCI6MTcxMTU0NDA3NywiZXhwIjoxNzExNjMwNDc3fQ.B4rREhfTgrBGqs7TIWpbprCXS1yQgCD-ezJJd6zBND4
Content-Type: application/json


###
GET  http://localhost:4000/api/structures/users/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NTcsImlhdCI6MTcxMTU0NDA3NywiZXhwIjoxNzExNjMwNDc3fQ.B4rREhfTgrBGqs7TIWpbprCXS1yQgCD-ezJJd6zBND4
Content-Type: application/json

###
DELETE http://localhost:4000/api/structures/delete/3

### 
GET http://localhost:4000/api/structures/responsable/1

###
POST  http://localhost:4000/api/users/createuser

{
    "firstname": "houyem",
    "lastname": "b",
    "email": "exemple@gmail.com",
    "password": "123",
    "phone": "0555555555",
    "isactive": true,
    "role": "magasinier"
}


### 
POST http://localhost:4000/api/bons/create/157
Content-Type: application/json

{
  "number": "1233",
  "orderdate": "2024-04-05",
  "deliverydate": "2024-04-10",
  "orderspecifications": "Sample order specifications",
  "status": "Pending",
  "id_fournisseur":"2",
  "productsOrdered": [
    {
      "productId": 23,
      "ordered_quantity": 5,
      "price":1000
    }
  ]
}

### 
POST  http://localhost:4000/api/bons/create-bon-reception/93
Content-Type: application/json

{
  "number": 99999,
  "id_magasinier": 136,
  "deliverydate": "2024-04-12",
  "products": [24,25],
  "receivedQuantities": [2,2]
}


### 
GET  http://localhost:4000/api/bons/allreceptions


###
GET  http://localhost:4000/api/bons/remaining-products/16 


###
POST  http://localhost:4000/api/fournisseur/create

{
    "name": "PC Store",
    "email": "pc@email.com",
    "phone": 123456789,
    "rc": "RC123456",
    "nif": 123456789,
    "rib": "12345678901234567890"
}

###
GET  http://localhost:4000/api/fournisseur/allFournisseurs

###
PUT  http://localhost:4000/api/fournisseur/update/pc@email.com

{
    "phone": 987654321
}

### 
DELETE  http://localhost:4000/api/fournisseur/delete/pc@email.com



###

GET http://localhost:4000/api/bons/allcomandsforresposnable/103
###
GET http://localhost:4000/api/bons/getAllBonCommandInterneFFordirectorMagazinier
Content-Type: application/json

{
  "role":"magazinier"
}
### create bon commane interne type =  decharge 



### create bon commane interne type = intene  
POST http://localhost:4000/api/bons/create-bon-commande-interne/143
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NTcsImlhdCI6MTcxMTU0NDA3NywiZXhwIjoxNzExNjMwNDc3fQ.B4rREhfTgrBGqs7TIWpbprCXS1yQgCD-ezJJd6zBND4
Content-Type: application/json

{ 
  "number": "123",
  "date": "2024-04-29",
  "typecommande": "Commande Decharges",
  "produitsCommandes": [
    { "id_produit": 5, "orderedquantity": 1 },
    { "id_produit": 4, "orderedquantity": 1 }
  ]
}

###
POST http://localhost:4000/api/bons/createBonDecharge/16
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NTcsImlhdCI6MTcxMTU0NDA3NywiZXhwIjoxNzExNjMwNDc3fQ.B4rREhfTgrBGqs7TIWpbprCXS1yQgCD-ezJJd6zBND4
Content-Type: application/json

{
  "date": "2024-04-29",
  "description": "Borrowing some products for a project",
  "id_magasinier":"140",
  "produitsdecharges": [
    { "id": 5, "quantity": 1 },
    { "id": 4, "quantity": 1}
  ]
}


###
POST http://localhost:4000/api/bons/receiveBonDecharge/17
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NTcsImlhdCI6MTcxMTU0NDA3NywiZXhwIjoxNzExNjMwNDc3fQ.B4rREhfTgrBGqs7TIWpbprCXS1yQgCD-ezJJd6zBND4
Content-Type: application/json

{
  "receiveddecharges": [
    { "id": 5, "dechargedquantity": 15},
    { "id": 4, "dechargedquantity":15}
  ]
}


### 
GET  http://localhost:4000/api/bons/getAllBonDecharges

### 
GET  http://localhost:4000/api/bons/getBonDechargeDetailsById/14


###
DELETE http://localhost:4000/api/bons/deleteBonDechargeById/18


### 
POST  http://localhost:4000/api/bons/create-bon-commande-interne/143
{
  "number": 80,
  "date": "2024-05-01",
  "produitsCommandes": [
    {
      "id_produit": 1,
      "orderedquantity": 10,
      "accordedquantity": 10
    }
  ]
}


###
GET http://localhost:4000/api/notifications/responsable/145

###
GET http://localhost:4000/api/notifications/magasinier/136

###
GET  http://localhost:4000/api/notifications/directeur/34

####
PATCH  http://localhost:4000/api/bons/validation/32


{
  "products": [
    {
      "id_produit": 1,
      "accordedquantity": 990
    }
  ]
}

### 
POST http://localhost:4000/api/bons/create-bon-sortie/18
Content-Type: application/json

{
  "service": "Some Service",
  "date": "2024-05-12",
  "observations": [
    { "id_produit": 25, "observation": "Observation for Product 1" },
    { "id_produit": 3, "observation": "Observation for Product 2" }
  ]
}


###

GET http://localhost:4000/api/pdf/pdfbonsortie/59


### 
GET http://localhost:4000/api/bons/command/details/61


###
GET http://localhost:4000/api/bons/receptionDetails/28



### 
GET http://localhost:4000/api/bons/remaining-products/93



###
GET http://localhost:4000/api/store/article/infos/6
###

POST http://localhost:4000/api/store/addProductByartcileId/13
Content-Type: application/json

{
  "productId" :3
}


###
POST http://localhost:4000/api/inventaire/create
{
  "number": 1,
  "date": "2024-05-20",
  "products": [
    {
      "produitId": 1,
      "physicalQuantity": 10,
      "observation": "Initial inventory count"
    },
    {
      "produitId": 4,
      "physicalQuantity": 20,
      "observation": "Initial inventory count"
    }
  ]
}

###
DELETE http://localhost:4000/api/inventaire/delete/15

###
UPDATE http://localhost:4000/api/inventaire/update/16
{
    "products": [
        {
            "id": 1,
            "physicalQuantity": 11
        },
        {
            "id": 4,
            "observation": "Updated inventory count for product 4"
        }
    ]
}

### 
GET http://localhost:4000/api/inventaire/details/16

###
PATCH http://localhost:4000/api/inventaire/validate/16

### 
GET http://localhost:4000/api/inventaire/all-etat