###
POST http://localhost:4000/api/auth/login
Content-Type: application/json

{
 "email": "f.bencharef@esi-sba.dz",
 "password": "fatima"
}
###
GET http://localhost:4000/api/users/AllUsers
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NTcsImlhdCI6MTcxMTU0NDA3NywiZXhwIjoxNzExNjMwNDc3fQ.B4rREhfTgrBGqs7TIWpbprCXS1yQgCD-ezJJd6zBND4
Content-Type: application/json

###
POST http://localhost:4000/api/users/createuser
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NTcsImlhdCI6MTcxMTU0NDA3NywiZXhwIjoxNzExNjMwNDc3fQ.B4rREhfTgrBGqs7TIWpbprCXS1yQgCD-ezJJd6zBND4
Content-Type: application/json

{
"firstname":"casRole",
"lastname":"casRole",
"email":"f.bencharef@esi-sba.dz",
"phone":"07777",
"password" : "abcd",
"isactive":true,
"role" : "admin"
}

### 

DELETE  http://localhost:4000/api/users/lasttest@gmail.com
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NTcsImlhdCI6MTcxMTU0NDA3NywiZXhwIjoxNzExNjMwNDc3fQ.B4rREhfTgrBGqs7TIWpbprCXS1yQgCD-ezJJd6zBND4
Content-Type: application/json

###

PUT  http://localhost:4000/api/users/modifyParams
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NTcsImlhdCI6MTcxMTU0NDA3NywiZXhwIjoxNzExNjMwNDc3fQ.B4rREhfTgrBGqs7TIWpbprCXS1yQgCD-ezJJd6zBND4
Content-Type: application/json

{
  "establishmentname" :"test3",
  "logo" :"test3",
  "tauxtva" : 20
}
###
PUT  http://localhost:4000/api/users/f.bencharef@esi-sba.dz
Content-Type: application/json

{
"firstname":"bencharef",
"lastname":" bencharef",
"email1":"f.bencharef@esi-sba.dz",
"phone":"07777",
"isactive":true,
"password" : "fatima",
"role" : "admin"
}


###
POST   http://localhost:4000/api/users/createbackups
 Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NTcsImlhdCI6MTcxMTU0NDA3NywiZXhwIjoxNzExNjMwNDc3fQ.B4rREhfTgrBGqs7TIWpbprCXS1yQgCD-ezJJd6zBND4
Content-Type: application/json

{
    "table" :["users"]
}
// dump an array of tale or default :all tables 
### 
GET   http://localhost:4000/api/users/getAllBackups
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NTcsImlhdCI6MTcxMTU0NDA3NywiZXhwIjoxNzExNjMwNDc3fQ.B4rREhfTgrBGqs7TIWpbprCXS1yQgCD-ezJJd6zBND4
Content-Type: application/json


### 
POST http://localhost:4000/api/auth/forgot-password
Content-Type: application/json

{
 "email": "f.bencharef@esi-sba.dz"
}
###

POST http://localhost:4000/api/auth/reset-password/e385545f-a886-4380-bcb6-442d87d05117
Content-Type: application/json

{
"newPassword":"fatima",
"confirmPassword":"fatima"
}